import type { Metadata } from "next";
import { Onest } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

const onest = Onest({ subsets: ["latin"], weight: ['500', '700'] });

export const metadata: Metadata = {
  title: "StudyBean",
  description: "Generated by create next app",
  icons: {
    icon: "/studybean-svg.svg",
    apple: "/apple-touch-icon.png"
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn("min-h-screen antialiased", onest.className)}>
        {children}
      </body>
    </html>
  );
}
